Traceback (most recent call last):
  File "simclr_transfer.py", line 418, in <module>
    model = Model(feature_dim, arch=args.arch).cuda()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
